# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e4c8062862d34a414288a020f759af045cf2a6e67155b54f85094e10aac764796ee0b8db83841394dbaac6ed0fe7e9dd293986779b1c290008519d2964a6c523

test:
  secret_key_base: 28b3628d629e24e04bbfdeca6fe89cc325d30d35e0f1ebf276c91527eaac8e3c40bc992c96bb7cadfbbe06fd5cd55081c7a02828df0ce89c9b9494322c30de27

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
